import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SharedLayout from "@/components/SharedLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-6 bg-gray-800 text-gray-300 fixed top-0 left-0 w-full z-10">
          <h1 className="text-3xl text-nowrap font-mono">
            <b>Online Library Management</b>
          </h1>
        </div>
        <SharedLayout />
        <main className="ml-[15rem] mt-20">{children}</main>
        {/* <footer className="bg-gray-800 text-gray-300 text-center p-4">
          <p>&copy; 2024 Online Library</p>
        </footer> */}
      </body>
    </html>
  );
}
